/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_IMGMATH__
#define __RUST_IMGMATH__
#ifdef __cplusplus
extern "C" {
#endif

/** <No documentation available> */
char *
blue_light_filter (
    double temperature,
    char const * input);

/** <No documentation available> */
void
rust_free_string (
    char * string);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_IMGMATH__ */
