/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_IMGMATH__
#define __RUST_IMGMATH__
#ifdef __cplusplus
extern "C"
{
#endif

#include <stddef.h>
#include <stdint.h>

    /** <No documentation available> */
    void
    blue_light_filter(
        double temperature,
        const char *input,
        const char *output);

#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_IMGMATH__ */
